<<<<<<< HEAD
version: "3.9"
   
services:
  my-app:
    image: sherlocked2019_web:latest
    ports:
      -8000:8000
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./data/db:/root/db
    environment:
      - SQLITE3_DB=db.sqlite3
  web:
    build: .
    command: python3.9 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
=======
version: "3"

services:
  sherlocked:
    restart: always
    build: .
    ports:
      - 8005:8000
    volumes:
      - type: volume
        source: database
        target: /sherlocked/database/
    command: >
      bash -c "python3 manage.py makemigrations
      && python3 manage.py migrate
      && /usr/local/bin/gunicorn sherlocked2019.wsgi:application -b :8000"

volumes:
  database:
>>>>>>> 75ed462eecedea6f7dceeed8f21b4ac3b43a0dea
